Resources:
  Ec2Instance:
  Type: AWS::EC2::Instance
  Properties:
    InstanceType: t2.micro
    AvailabilityZone: us-west-1a
    ImageId: ami-015e832ac6a60f0de
    Tags:
      - Key: Name
        Value: Eugenie